codeforjapan/OpenDataTools

datamanager/nodejs/utils/multibyte.test.ts, datamanager/nodejs/utils/multibyte.ts
#22 
複数のバリデーターで使われる可能性があるので、全角検知と半角検知の両方をUtil直下に書きました。テストは通ってますが正規表現に若干自信なし :(
=> 全角文字検出・半角文字検出のUtil関数を追加

datamanager/nodejs/items/validator/tel.test.ts, datamanager/nodejs/items/validator/tel.ts
close #11 
考え方は #11 のissueにメモしています。
国内電話と国際電話の先頭記述のチェックに重きを置いて、どこで区切るかはチェックしていません。
国際電話の記述ルールが少し複雑なこともあって、テストケースが足りていないかもしれません。。
もしかしたら国内電話と国際電話でエラー判定を分けたほうがいいかもしれないです。そのあたりアドバイスいただけると助かります 🙏
=> Add tel validator

webclient/src/App.tsx
chakraが二重でimportされているため削除しました。
=> 二重でimportされた部分を削除

datamanager/nodejs/items/validator/regcode.test.ts, datamanager/nodejs/items/validator/regcode.ts
=> Add Region Code Validator

datamanager/nodejs/items/validator/no.test.ts, datamanager/nodejs/items/validator/no.ts
=> Add NO Code Validator

webclient/package.json, webclient/src/features/map/routes/Map.tsx, webclient/yarn.lock
確認用の地図を表示するようにしました。
今はまだサンプルで山手線の駅を表示しています。
読み込んだ csv ファイルから緯度、経度を抽出して表示するときには、Map.tsx の const points を差し替えてください。
使用している Geolonia Maps は、localhost 上のテスト環境や、本番環境でも GitHub Pages（https://*.github.io）(※ 独自ドメインは対象外)、Netlify (https://*.netlify.com, https://*.netlify.app) (※ 独自ドメインは対象外) では料金が発生しません。
Ref. https://docs.geolonia.com/tutorial/002/#%E5%AF%BE%E8%B1%A1%E3%81%A8%E3%81%AA%E3%82%8B-url-%E3%81%8A%E3%82%88%E3%81%B3%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9
=> 確認用の地図を表示する。（今はまだサンプルで山手線の駅を表示しています）

webclient/src/components/Elements/Dataset/NormalizeDatasetItemLabel.tsx, webclient/src/components/Elements/OstInput/OstInput.tsx, webclient/src/components/Elements/OstLink/OstLink.tsx, webclient/src/components/Elements/OstSelect/OstSelect.tsx, webclient/src/features/auto-convert/routes/AutoConvert.tsx, webclient/src/features/data-editor/routes/DataEditor.tsx, webclient/src/features/home/routes/Home.tsx, webclient/src/features/normalize-label/routes/NormalizeLabel.tsx
close #74 
- 置き換えられるところについて、Ostコンポーネントに置き換えました。
- Ostコンポーネントのpropsを拡張しています。
- onChangeにあたるものをpropsに追加
- router linkのtoにあたるものをpropsに追加
=> [webclient]chakra-uiをOstコンポーネントに置き換え

webclient/src/components/Editor/DataEditorMain.tsx, webclient/src/components/Editor/DataEditorSidenav.tsx, webclient/src/features/data-editor/routes/DataEditor.tsx, webclient/src/theme/foundations/colors.ts
=> [webclient]data-editor画面のスタイルを調整

webclient/src/features/upload/routes/FileUpload.tsx
`yarn format:prettier` をかけました。
=> prettier整形

datamanager/nodejs/index.ts, datamanager/nodejs/items/validator/regname.test.ts, datamanager/nodejs/scheme/validator.test.ts, datamanager/nodejs/scheme/validator.ts, webclient/src/features/auto-convert/routes/AutoConvert.tsx, webclient/src/features/data-editor/routes/DataEditor.tsx, webclient/src/features/upload/routes/FileUpload.tsx, webclient/src/hooks/useDataset.ts, webclient/src/routes/public.tsx, webclient/src/stores/recoil_keys.ts, webclient/src/stores/upload_file.ts, webclient/yarn.lock
MAP関連のタスクができるように、データのインポートから編集、マップ表示までをできるようにしました。
また、webclientからdatamanagerのschemeValidator.getMissingItemsを呼び出せるようにして、足りていない項目を取得できるようにしました。
=> issue85を部分的とissue102を実装

webclient/src/features/upload/routes/FileUpload.tsx
- close #103 
CSVファイルが複数ドロップされた場合の処理を追加しました。
表示されるテキストは仮で入力してあります。
=> 【webclient】CSVファイルを複数ドロップした際の処理を追加

webclient/src/components/Layout/StepLayout.tsx, webclient/src/features/auto-convert/routes/AutoConvert.tsx, webclient/src/features/normalize-label/routes/NormalizeLabel.tsx
close #124 
SSIA
ステップ２のprogressバーが復活しました。
=> auto-convertのルーティング変更（uidの削除）に対応

webclient/src/components/Editor/DataEditorMain.tsx
close #121 
セルデータ編集ページの各セルに対し、行番号と名称が表示されるようにしました。
=> セルデータ編集ページで行番号と名称を表示

webclient/src/components/Editor/DataEditorMain.tsx, webclient/src/components/Editor/DataEditorSidenav.tsx
close #130 
SSIA
ステップ４に遷移したときにメインエリアは編集UIが表示されるようにしました。
=> ステップ4に遷移時、datasetItemListの最初のactive項目を選択状態にする

webclient/src/components/Head/Head.tsx, webclient/src/components/Layout/MainLayout.tsx
close #135 
- フッターを削除しました
- titleテキストを差し替えました
=> フッター削除・title差し替え

datamanager/nodejs/items/validator/barrierFreeInfo.test.ts, datamanager/nodejs/items/validator/barrierFreeInfo.ts
#21 はチェックする方法がないということで、一旦クローズしていたのですが、文字列チェックだけでもしておいたほうが良いと思ったので、その実装を PR にしました。
=> バリアフリー情報をチェックする。 #21

datamanager/nodejs/items/validator/address.test.ts, datamanager/nodejs/items/validator/address.ts, datamanager/nodejs/package.json, datamanager/nodejs/yarn.lock
normalize が非同期処理なので、validateDataType に async をつけました。
=> 住所が正しいかどうかをチェックする。

webclient/src/components/Editor/DataEditorSidenav.tsx
=> fix: rm wastefull func

webclient/src/features/auto-convert/routes/AutoConvert.tsx, webclient/src/features/upload-for-map/routes/FileUploadForMap.tsx
読み込んだCSVファイルに含まれる不要な空行を、パース時に削除するように修正しました。
=> CSVファイル中の不要な空行を削除

webclient/src/components/Editor/DataEditorLatLng.tsx, webclient/src/components/Editor/MapEditorModal.tsx
- 123.111100 のように0でおわっていると勝手に4桁に丸められちゃうので、あえて6桁にするように
- メイン画面のinputを入力不可に
- Input要素のラベルを追加
=> 緯度経度入力インターフェースのエラー修正

webclient/src/features/map/routes/Map.tsx
=> マップ画面が全画面で表示されるように修正

webclient/src/components/Layout/StepLayout.tsx, webclient/src/features/auto-convert/routes/AutoConvert.tsx, webclient/src/features/data-editor/routes/DataEditor.tsx, webclient/src/features/normalize-label/routes/NormalizeLabel.tsx, webclient/src/features/upload/routes/FileUpload.tsx
=> add introduction message to each steps

datamanager/nodejs/scheme/formatters/item_label.ts
=> change availableDateTimeAdditional value

webclient/src/features/normalize-label/routes/NormalizeLabel.tsx, webclient/src/hooks/useDataset.ts, webclient/src/stores/dataset.ts, webclient/types/dataset.d.ts
データのインポート時にindexedDBに保存するのに時間がかかるので、いったんsetTimeoutでデータ数に合わせて対処。
根本的に解決するためにはindexedDBのモデルをすこし変えないといけないので暫定処理
=> fix import bug

webclient/src/components/Elements/OstLink/OstNavLink.tsx, webclient/src/theme/components/button.ts
avatar内のアイコンがいつの間にか白くなっていたので修正しました。
=> avatarのスタイルを追加
